// Full source-file viewer for the DXF library. Each preview SVG is
// the entire DXF modelspace rendered via ezdxf's SVG backend (handles
// HATCH / MTEXT / INSERT / colours / lineweights correctly — way more
// faithful than my hand-rolled per-entity converter).
//
// Generated by `python md/dxf_to_preview.py`. Access via the `#/dxf`
// hash route.

import { useState } from 'react';

const previewUrls = import.meta.glob<string>(
  '/public/cards/dxf_previews/*.svg',
  { eager: true, import: 'default', query: '?url' },
) as Record<string, string>;

interface Preview {
  name: string;
  url: string;
}

const ALL: Preview[] = Object.entries(previewUrls)
  .map(([absPath, url]) => {
    const filename = absPath.split('/').pop() ?? '';
    return { name: filename.replace(/\.svg$/, ''), url };
  })
  .sort((a, b) => a.name.localeCompare(b.name, 'zh'));

export function DxfPreview() {
  const [selected, setSelected] = useState<Preview | null>(ALL[0] ?? null);
  return (
    <div style={{ display: 'flex', height: '100vh', background: 'var(--bg)', color: 'var(--pen)' }}>
      <aside
        style={{
          width: 260,
          borderRight: '1px solid rgba(255,255,255,0.15)',
          padding: 12,
          overflowY: 'auto',
          fontFamily: "'Patrick Hand', sans-serif",
        }}
      >
        <h2 style={{ margin: '0 0 12px 0' }}>📐 DXF Sources</h2>
        <p style={{ color: 'var(--pen-soft)', fontSize: '0.85rem', marginTop: 0 }}>
          {ALL.length} file(s) rendered from <code>D:\DXF_IN</code>. Click to view.
        </p>
        {ALL.map((p) => (
          <button
            key={p.name}
            type="button"
            onClick={() => setSelected(p)}
            style={{
              display: 'block',
              width: '100%',
              textAlign: 'left',
              padding: '8px 10px',
              marginBottom: 6,
              background: selected?.name === p.name ? 'rgba(255,225,105,0.12)' : 'transparent',
              border: '1px solid rgba(255,255,255,0.12)',
              borderRadius: 4,
              color: 'var(--pen)',
              cursor: 'pointer',
              fontFamily: "'Patrick Hand', sans-serif",
              fontSize: '0.9rem',
              wordBreak: 'break-all',
            }}
          >
            {p.name}
          </button>
        ))}
      </aside>
      <main style={{ flex: 1, overflow: 'auto', padding: 16, background: 'rgba(0,0,0,0.20)' }}>
        {selected ? (
          <>
            <header style={{ marginBottom: 12, fontFamily: "'Patrick Hand', sans-serif" }}>
              <h3 style={{ margin: 0 }}>{selected.name}</h3>
              <a
                href={selected.url}
                target="_blank"
                rel="noreferrer"
                style={{ color: 'var(--accent)', fontSize: '0.85rem' }}
              >
                open SVG in new tab ↗
              </a>
            </header>
            {/* Each preview SVG has its own viewBox set by ezdxf; let the
                browser scale to width and keep aspect. */}
            <img
              src={selected.url}
              alt={selected.name}
              style={{
                width: '100%',
                height: 'auto',
                display: 'block',
                background: 'rgba(255,255,255,0.04)',
              }}
            />
          </>
        ) : (
          <p style={{ color: 'var(--pen-soft)' }}>No previews yet — run <code>python md/dxf_to_preview.py</code>.</p>
        )}
      </main>
    </div>
  );
}
